/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.una.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test public void testGetMessage() {
        assertEquals("1", "1");
    }
}
