name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Make Static Server gradlew executable
        run: chmod +x static-server/gradlew
      - name: Make Router gradlew executable
        run: chmod +x router/gradlew
      - name: Wrap Static Server
        run: |
          cd static-server
          gradle wrapper
          cd ..
      - name: Wrap Router
        run: |
          cd router
          gradle wrapper
          cd ..
      - name: Build Static Server with Gradle
        run: static-server/gradlew build
      - name: Build Router with Gradle
        run: router/gradlew build
