# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Package Router with Maven
      run: mvn -B package --file "./E-Nano2020 Router/pom.xml"
    - name: Package Static Server with Maven
      run: mvn -B package --file "./E-Nano2020 Static Server/pom.xml"
